apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cternal
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cternal
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
